### ISSUE TITLE
_1basic.t and constants.t fails on Arch Linux

### ISSUE THREAD

**Issue by trizen** [sisyphus/math-mpfr#1]
The version of the pre-compiled MPFR library provided by Arch Linux (https://www.archlinux.org/packages/core/i686/mpfr/) has a suffix version, which makes the third test (from `t/_1basic.t`) to fail with the following message:

```
not ok 3 - Header and Library do not match
```

and the fifth test from `t/constants.t` to fail with:

```
not ok 5 3.1.3-p5 is not the same as 3.1.3
```

The value of `Rmpfr_get_version` is `3.1.3-p5`, while the value of `MPFR_VERSION_STRING` is `3.1.3`. I think this also affects other Linux distributions.

A simple fix would be removing the suffix from `Rmpfr_get_version` to match `MPFR_VERSION_STRING`, or maybe changing the test like this:

``` perl
{
    my $v1 = Rmpfr_get_version();
    my $v2 = MPFR_VERSION_STRING;
    $v1 =~ s/-.*//;                 # remove any version suffix
    $v2 =~ s/-.*//;                 # =//=
    if($v1 eq $v2) {print "ok 3\n"}
    else {
        print "not ok 3 - Header and Library do not match ('$v1' ne '$v2')\n"
    }
}
```

**Comment by sisyphus** [comment]
I've not seen this problem before, despite the large number of successful tests run on Linux by the cpan-testers - other distros apparently ensure that mpfr_get_version() and MPFR_VERSION_STRING match. 
I'm actually thinking that someone forgot to edit the MPFR_VERSION_STRING entry in mpfr.h.
Would you be able to check with them as to whether that's the case ?

I'm a bit loathe to remove the suffix from the test for two reasons:
1) I think mpfr_get_version() and MPFR_VERSION_STRING should match exactly;
2) we would then fail to detect a discrepancy between 3.1.3-p5 and (say) 3.1.3-p6.

Perhaps the second point doesn't really apply ... perhaps 3.1.3-p5 headers are guaranteed to be compatible with the 3.1.3-p6 library  ... I don't know.

If they insist on distributing mpfr packages where header and library can disagree on the version string, then I guess I'll have to do as you suggest - but only for those machines that might have installed the ArchLinux distros.

On Windows, Ubuntu and Debian, I build Math::MPFR against svn trunk, where both Rmpfr_get_version() and MPFR_VERSION_STRING() report "3.2.0-dev".

Cheers,
Rob

**Comment by trizen** [comment]
It was my mistake. I apologize for it. Somehow, I had an old `mpfr.h` file in `/usr/local/include/` which took precedence over `/usr/include/mpfr.h`. By removing it, `Math::MPFR` passes all the tests.

Thank you for your patience.
