### ISSUE TITLE
NOK_and_POK failures in Math::MPFR-4.21 for perl-5.35.10

### ISSUE THREAD

**Issue by hvds** [sisyphus/math-mpfr#4]
As a result of https://github.com/Perl/perl5/commit/b1e3ba27cd, the tests of `Inf` and `NaN` in this test file are now failing. Because of the accumulating nature of `$check`, that then causes a cascade of failures through the rest of the test file.

Please see the commit message for full details of what changed, and https://github.com/Perl/perl5/issues/19550 for the original report. I suspect `Math::MPFR` just needs to tweak a couple of tests here.

**Comment by sisyphus** [comment]
Thanks @hvds.
I'll deal with this soon, and then close.

**Comment by sisyphus** [comment]
All now fixed
